server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/user_db_test}
    username: ${USER_DB_USERNAME:postgres}
    password: ${USER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO