server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_backend_test
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.com.company.mobilebackend=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never