spring.application.name=order-service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
services.product.url=http://localhost:8082
spring.cloud.openfeign.client.config.product-service.connectTimeout=${PRODUCT_CONNECT_TIMEOUT_MS:2000}
spring.cloud.openfeign.client.config.product-service.readTimeout=${PRODUCT_READ_TIMEOUT_MS:3000}
spring.cloud.openfeign.client.config.product-service.loggerLevel=basic
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.level.com.blackroth.training.orderservice=INFO
logging.level.org.springframework.cloud.openfeign=INFO