spring.application.name=order-service

spring.config.import=optional:configserver:http://localhost:8888

spring.profiles.active=dev

# =========================================================
# DATABASE
# =========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# EUREKA
# =========================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# =========================================================
# OPENFEIGN
# =========================================================
spring.cloud.openfeign.circuitbreaker.enabled=true

# Default Feign timeout
spring.cloud.openfeign.client.config.default.connectTimeout=2000
spring.cloud.openfeign.client.config.default.readTimeout=3000

# Product Service Feign timeout
spring.cloud.openfeign.client.config.product-service.connectTimeout=2000
spring.cloud.openfeign.client.config.product-service.readTimeout=3000

# =========================================================
# RESILIENCE4J CIRCUIT BREAKER
# =========================================================
resilience4j.circuitbreaker.instances.productService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.productService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.productService.automaticTransitionFromOpenToHalfOpenEnabled=true

# =========================================================
# RESILIENCE4J RETRY
# =========================================================
resilience4j.retry.instances.productService.maxAttempts=3
resilience4j.retry.instances.productService.waitDuration=500ms

# =========================================================
# ACTUATOR
# =========================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =========================================================
# JWT
# =========================================================
app.jwt.secret=your-very-long-random-secret-key-change-this-in-production-min-256-bits